package com.practice.core.model;

public enum ErrorCode {
    DELIVERY_NOT_FOUND,
    DELIVERY_ALREADY_EXISTS,
    DELIVERY_ALREADY_DELIVERED,

    STATUS_REQUIRED,
    STARTED_AT_REQUIRED,

    DELIVERY_FINISHED_AT_REQUIRED,
    DELIVERY_FINISHED_AT_NOT_ALLOWED,
    FINISHED_AT_BEFORE_STARTED_AT,

    VEHICLE_ID_REQUIRED,
    ADDRESS_REQUIRED,
    STARTED_AT_IN_FUTURE,
    INTERNAL_SERVER_ERROR,
    DATA_INTEGRITY_VIOLATION,
    MALFORMED_REQUEST,
    VALIDATION_FAILED,
    INVALID_REQUEST_PARAMETER
}
