spring:
  application:
    name: spring-base
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/deliverydb}
    username: ${SPRING_DATASOURCE_USERNAME:delivery}
    password: ${SPRING_DATASOURCE_PASSWORD:delivery}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  flyway:
    enabled: true
    validate-on-migrate: true
  lifecycle:
    timeout-per-shutdown-phase: 30s

server:
  shutdown: graceful

info:
  app:
    name: ${spring.application.name}
    version: ${project.version}

  level:
    root: INFO
    org.practice.core: INFO

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never

  metrics:
    tags:
      application: ${spring.application.name}

logging:
  structured:
    format:
      console: ecs